---

# Configure HAproxy
- name: "Create haproxy service config files"
  template:
    src: haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
  notify: Restart haproxy
  tags:
    - haproxy-service-config