---

# Install HAproxy

- name: "Install haproxy RedHat Packages"
  yum:
    pkg: "{{ item }}"
    state: latest
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: haproxy_yum_packages
  tags:
    - haproxy-packages
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'